// <auto-generated />
using System;
using Elijah.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Elijah.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251201204818_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Elijah.Domain.Entities.ConfiguredReporting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attribute")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Changed")
                        .HasColumnType("boolean");

                    b.Property<string>("Cluster")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("boolean");

                    b.Property<string>("MaximumReportInterval")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MinimumReportInterval")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReportableChange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SysCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<DateTimeOffset?>("SysModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<bool>("SysRemoved")
                        .HasColumnType("boolean")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("ConfiguredReporting");
                });

            modelBuilder.Entity("Elijah.Domain.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeviceTemplateId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Subscribed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("SysCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<DateTimeOffset?>("SysModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<bool>("SysRemoved")
                        .HasColumnType("boolean")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.HasIndex("DeviceTemplateId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Device");
                });

            modelBuilder.Entity("Elijah.Domain.Entities.DeviceFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<string>("FilterValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SysCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<DateTimeOffset?>("SysModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<bool>("SysRemoved")
                        .HasColumnType("boolean")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("DeviceFilter");
                });

            modelBuilder.Entity("Elijah.Domain.Entities.DeviceTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfActive")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SysCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<DateTimeOffset?>("SysModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<bool>("SysRemoved")
                        .HasColumnType("boolean")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("ModelId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DeviceTemplate");
                });

            modelBuilder.Entity("Elijah.Domain.Entities.OpenTherm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IntervalSec")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SysCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<DateTimeOffset?>("SysModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<bool>("SysRemoved")
                        .HasColumnType("boolean")
                        .HasColumnOrder(3);

                    b.Property<float>("Threshold")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("OpenTherm");
                });

            modelBuilder.Entity("Elijah.Domain.Entities.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SysCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<DateTimeOffset?>("SysModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.Property<bool>("SysRemoved")
                        .HasColumnType("boolean")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("Option");
                });

            modelBuilder.Entity("Elijah.Domain.Entities.ConfiguredReporting", b =>
                {
                    b.HasOne("Elijah.Domain.Entities.Device", "Device")
                        .WithMany("ConfiguredReportings")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Elijah.Domain.Entities.Device", b =>
                {
                    b.HasOne("Elijah.Domain.Entities.DeviceTemplate", "DeviceTemplate")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceTemplate");
                });

            modelBuilder.Entity("Elijah.Domain.Entities.DeviceFilter", b =>
                {
                    b.HasOne("Elijah.Domain.Entities.Device", "Device")
                        .WithMany("DeviceFilters")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Elijah.Domain.Entities.Option", b =>
                {
                    b.HasOne("Elijah.Domain.Entities.Device", "Device")
                        .WithMany("Options")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Elijah.Domain.Entities.Device", b =>
                {
                    b.Navigation("ConfiguredReportings");

                    b.Navigation("DeviceFilters");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("Elijah.Domain.Entities.DeviceTemplate", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
